FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    curl \
    git \
    gpg \
    unzip \
    zip

RUN \curl -sSL "https://get.rvm.io" | bash
RUN echo "source /etc/profile.d/rvm.sh" >> /etc/bash.bashrc

RUN /bin/bash -c "source /etc/profile.d/rvm.sh; rvm install ruby-2.6.5"
